title: Joan Medina Roca
tagline: Escriptura creativa i ficció en Català
description:
  Blog de <a href="https://blog.joanmedinaroca.com/qui-soc">Joan Medina Roca</a>.
  <br />
  Escriptura creativa, històries curtes, novel·la i articles d'opinió.
url: "https://blog.joanmedinaroca.com"
baseurl: ""
paginate: 5
permalink: /:slug/
author:
  name: Mark Otto
  url: "https://twitter.com/mdo"
  email: markdotto@gmail.com
plugins:
  - jekyll-paginate
version: 1.1.0
google_analytics_id: null
